/**
 * Sample Book Data
 * 
 * A pre-built watercolor memory book example: "As Memórias do Papai"
 * A daughter creating a memory book for her father with Alzheimer's.
 * 
 * This data is displayed on the landing page and dashboard as a showcase.
 * Images were generated by the pipeline using Gemini 2.5 Flash Image.
 * 
 * The sample book supports i18n: text content adapts to the selected language
 * while images remain the same.
 */

import type { BookPage } from '../components/book/BookViewer';
import { translations } from '../constants/translations';
import type { LanguageCode } from '../constants/translations';

// Import generated images
import coverImg from '../assets/sample-book/cover.png';
import page1Img from '../assets/sample-book/page-1.png';
import page2Img from '../assets/sample-book/page-2.png';
import page3Img from '../assets/sample-book/page-3.png';
import page4Img from '../assets/sample-book/page-4.png';
import page5Img from '../assets/sample-book/page-5.png';
import page6Img from '../assets/sample-book/page-6.png';
import page7Img from '../assets/sample-book/page-7.png';
import page8Img from '../assets/sample-book/page-8.png';
import page9Img from '../assets/sample-book/page-9.png';
import page10Img from '../assets/sample-book/page-10.png';
import backCoverImg from '../assets/sample-book/back-cover.png';

// Page images in order (cover, 10 pages, back cover)
const PAGE_IMAGES = [coverImg, page1Img, page2Img, page3Img, page4Img, page5Img, page6Img, page7Img, page8Img, page9Img, page10Img, backCoverImg];
const PAGE_DATES = ['cover', 'young', 'young', 'adolescent', 'adolescent', 'adult', 'adult', 'adult', 'adult', 'elderly', 'elderly', 'cover'];

// ============================================================================
// Language-aware sample book pages
// ============================================================================

export function getSampleBookPages(lang: LanguageCode): BookPage[] {
    const sb = (translations[lang] as Record<string, unknown>)?.sampleBook as {
        bookTitle: string;
        bookDescription: string;
        pages: { title: string; description: string }[];
        backCoverDescription: string;
    } | undefined;

    // Fallback to Portuguese if translations not found
    const fallback = translations.pt.sampleBook;
    const source = sb || fallback;

    const pages: BookPage[] = [
        // Cover
        {
            id: 'cover',
            imageUrl: PAGE_IMAGES[0],
            title: source.bookTitle,
            description: source.bookDescription,
            date: PAGE_DATES[0],
        },
    ];

    // Content pages (1-10)
    for (let i = 0; i < 10; i++) {
        const pageData = source.pages[i];
        pages.push({
            id: `page-${i + 1}`,
            imageUrl: PAGE_IMAGES[i + 1],
            title: pageData?.title || `Page ${i + 1}`,
            description: pageData?.description || '',
            date: PAGE_DATES[i + 1],
        });
    }

    // Back cover
    pages.push({
        id: 'back-cover',
        imageUrl: PAGE_IMAGES[11],
        title: translations[lang]?.bookViewer?.backCover || 'Contracapa',
        description: source.backCoverDescription,
        date: PAGE_DATES[11],
    });

    return pages;
}

// Default export (Portuguese) for backward compatibility
export const SAMPLE_BOOK_PAGES: BookPage[] = getSampleBookPages('pt');

// ============================================================================
// Sample Book Display Data (for MemoryStoryCard)
// ============================================================================

export interface SampleBookDisplay {
    id: string;
    title: string;
    date: string;
    description: string;
    imageUrl: string;
    pageImages: string[];
    isFavorite: boolean;
    pageCount: number;
    status: string;
    imageStyle: string;
    isSample: boolean;
}

export function getSampleBookDisplay(lang: LanguageCode): SampleBookDisplay {
    const sb = (translations[lang] as Record<string, unknown>)?.sampleBook as {
        bookTitle: string;
        displayDate: string;
        displayDescription: string;
    } | undefined;

    const fallback = translations.pt.sampleBook;
    const source = sb || fallback;

    return {
        id: 'sample-book-watercolor',
        title: source.bookTitle,
        date: source.displayDate,
        description: source.displayDescription,
        imageUrl: coverImg,
        pageImages: PAGE_IMAGES,
        isFavorite: true,
        pageCount: 12,
        status: 'completed',
        imageStyle: 'watercolor',
        isSample: true,
    };
}

// Default export (Portuguese) for backward compatibility
export const SAMPLE_BOOK_DISPLAY: SampleBookDisplay = getSampleBookDisplay('pt');

// ============================================================================
// Sample Wizard Form Data (for generating via backend pipeline)
// ============================================================================

export const SAMPLE_WIZARD_DATA = {
    bookSetup: {
        pageCount: 10,
        referenceInputMode: 'characteristics' as const,
        physicalCharacteristics: {
            name: 'Carlos',
            gender: 'male' as const,
            skinColor: 'medium' as const,
            hairColor: 'gray' as const,
            hairStyle: 'short' as const,
            hasGlasses: true,
            hasFacialHair: false,
        },
        referencePhotos: [],
        illustrationStyle: 'watercolor' as const,
        title: 'As Memórias do Papai',
        subtitle: 'Uma homenagem de amor da sua filha',
        date: '2026-02-14',
    },
    childhood: {
        birthPlace: 'Interior de Minas Gerais, numa casa amarela com quintal grande',
        parents: 'Dona Rosa e Seu Antônio, pessoas simples e trabalhadoras do campo',
        siblings: 'Três irmãos mais novos: Pedro, Ana e João',
        happyMemory: 'Correr descalço no quintal da casa amarela, perseguindo borboletas entre as árvores de manga nas tardes quentes de verão',
        enjoyedActivities: 'Subir em árvores, pescar no riacho com o avô, ouvir histórias da vovó antes de dormir',
        photos: [],
    },
    teenage: {
        livingPlace: 'Mudou para a cidade pequena para estudar no colegial',
        schoolExperiences: 'Primeiro da família a completar os estudos. Estudava de manhã e ajudava na mercearia do tio à tarde',
        friendsInterests: 'Apaixonado por futebol, jogava todas as tardes no campinho do bairro com os amigos. Sonhava em ser jogador profissional',
        memorableEvents: 'A formatura do colégio foi um marco — a avó chorou de alegria e o avô disse que era o dia mais feliz da vida dele',
        photos: [],
    },
    adultLife: {
        career: 'Trabalhou como professor de matemática por 35 anos. Era conhecido por transformar números em histórias',
        hobbiesPassions: 'Adorava jardinagem, café coado na hora e contar piadas que só ele achava engraçadas',
        partner: 'Casou-se com Maria Helena numa manhã de sol. Quando a viu no altar, esqueceu o discurso ensaiado e só conseguiu sorrir',
        children: 'Uma filha: Ana Clara. Quando ela nasceu, segurou-a nos braços e prometeu que estaria sempre ali para ela',
        milestones: 'Ensinou a filha a andar de bicicleta no parque. Corria ao lado segurando o banco, repetindo "Eu estou aqui." Até que num momento mágico, soltou — e ela voou sozinha',
        photos: [],
    },
    laterLife: {
        livingPlace: 'Mora com a família na mesma casa onde criou a filha',
        routinesTraditions: 'Todas as manhãs toma café no jardim olhando as flores que plantou. Às tardes, gosta de sentar na varanda ouvindo música antiga',
        familyMoments: 'O último Natal em família foi especial — sentou na cabeceira da mesa cercado por filhos e netos. Mesmo quando as palavras faltam, o sorriso diz tudo',
        comfortJoy: 'O som da risada dos netos, o cheiro do café, e os álbuns de fotos antigos que a filha mostra todos os dias',
        photos: [],
    },
    generationSettings: {
        readingLevel: 'standard' as const,
        tone: 'warm' as const,
    },
};
